language: python
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/download"
env:
  global:
  - TEST_DIR=/tmp/test_dir/
  - MODULE=pipegraph
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true" NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1"
    CYTHON_VERSION="0.23.4" PANDAS_VERSION="0.22.0" NETWORKX_VERSION="2.0"
install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
deploy:
  provider: pypi
  user: pinguy
  distributions: sdist
  password:
    secure: Pv43HMo3B7/YM13GXtHXYoDO2huYXCU07LLxmawftafB0DyKI068Bhb70Nf0Ror1Y9Yp0EeN1rlJcXh62C7S1n4byGTMw9ws1EwqC14rC2hzrvoseJwXw3FeTRDcHWsjqzrGhMc01/BVEnIC+zAkmIUsreXHgquu6MXHk/Qv6wJPyCvtiL+jGhYrzD3XKYHosrtnCdRitzc+JS9Y3WXGdZDphNkX9qE9bwrRrePMJ+FcjINuHMaNy7xzLt2eq934YCkz23R39w1ijzeLxalnq/uZGcm+794tFGu7zJM+MXDxkblpymAThwdqNpi/Yz127VVeZsaag2CoJpml4s4WsW1JyE8JbKfWJLx0do8JIGU+QPsjsOMtE8x4y92A8jm3fhtsjLLmcIvtb0PBgX68DWBwEy12hRXuXjs6f/2esolW/BOjBHtWmCHIN1FL9HL/c+leCroBryCYZonjZD352GLf3QHaU+40zBa0aVem4zaEHYlfUHeVqDqr+q1QLj3+RZrplwt6iOXQlrEVgZaeXj129p96coyFwajVqUcs1YyVheqAeEb4cp1ydvhyMiMsbfKK2wIcdlL1SCag03+HNfIpGRQfwtEVBuK6aDTru/CxruCPme/6z/dqRejUdgqDWn1Ck+mT2ShdhDmPn/hViRM1+xWn+IFSmqqsf9OYqVA=
  on:
    branch: master
  server: https://pypi.python.org
