language: python
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/download"
env:
  global:
  - TEST_DIR=/tmp/test_dir/
  - MODULE=pipegraph
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true" NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1"
    CYTHON_VERSION="0.23.4" PANDAS_VERSION="0.22.0" NETWORKX_VERSION="2.0"
install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
deploy:
  provider: pypi
  user: pinguy
  distributions: sdist
  password:
    secure: oZeVX0k4Vjm4KKX2Z49a4DaoexY1v39Yme9TevGXBzkrfApu/nsakHXgFDGwHHefVqK83Y3B3HbMSi49XlO4NJx9MYas2jAwI8mLUCV0avaKzewL4cR+IHtPVO8SbJAJc+wOvH4rwNurBTzvyjJ1LGqENpg+2YZPObdKBRIAlCsn0lBwymdvd1cWAaMScHJuE2A8uKGgYrM6fYW2GuLSi6T0fCojKbzVjGq+EeWiBitiYxPLJ0bGV2T8Mx9tab2i4qv7C72dVgoWptVtCPCtptvMLO6H3dNyult15jlYfUhoIe3GoMmt757l5qeokeEo2m4Ct1VqpJU+HEOJoF/wlC614yxbRprND0f2AfowI1lTxtZEbNKUsmktXSxYNU/jWp+LxBc8mef/FG2Y2xlOg2wPWVKmdcJlnsPV10kIKUmq3F0ZSr1sCSC6uFcbPjrlIKFH2ft+0FLF42by6nQSjrTPJ8sSDUm+xGNU1af4Ok/TabRpjuJRBsmORqEVA9M9v/qDv5ukZpN4giwUPSEBRKjoCzCqA+lsTnCfhEvt0C2sygXZQOqlG+ZrpKAnIfCWa+fJpXO7LqPWLcNs+vkCuf2OlFfXZgXinvH8jdXpc8upWI5+P9aXmCKP48Uj0jhQxaeUp99SRY93vzwKR752hHE8V4h2RtMuk3x3hyWn9DM=
  on:
    branch: develop
  server: https://test.pypi.org/legacy/
