# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: mcasl/circleci_pipegraph:0.0.1
    steps:
      - checkout
      - run:
            name: Make html
            command: |
               . $HOME/venv/bin/activate
               python setup.py clean
               sudo python setup.py develop
               set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
               sudo cat ~/log.txt && if grep -q "Traceback (most recent call last):" ~/log.txt; then false; else true; fi

  deploy:
    machine:
        enabled: true
    working_directory: ~/master
    steps:
      - checkout
      - run:
          name: Deploy Master
          command: |
            - bash ci_scripts/circleci/push_doc.sh
      - store_artifacts:
          path: doc/_build/html
          destination: ~/log.txt
    branches:
      ignore:
        - gh-pages
