# Modified from https://github.com/scikit-learn-contrib/imbalanced-learn/blob/master/.circleci/config.yml
version: 2

jobs:
  python3:
    docker:
      - image: circle/python:3.6.1
    environment:
      - USERNAME: "mcasl"
      - DOC_REPO: "PipeGraph"
      - DOC_URL: ""
      - EMAIL: "manuel.castejon@gmail.com"
      - MINICONDA_PATH: ~/miniconda
      - CONDA_ENV_NAME: testenv
      - PYTHON_VERSION: 3
    steps:
      - checkout
      - run: ./build_tools/circle/checkout_merge_commit.sh
      - run: ./build_tools/circle/build_doc.sh
      - store_artifacts:
          path: doc/_build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: doc/_build/html
          paths: .
      - attach_workspace:
          at: doc/_build/html
      - run: ls -ltrh doc/_build/html
      # - deploy:
      #     command: |
      #       if [[ "${CIRCLE_BRANCH}" =~ ^master$|^[0-9]+\.[0-9]+\.X$ ]]; then
      #         bash ./build_tools/circle/push_doc.sh doc/_build/html
      #       fi
    filters:
      branches:
        ignore: gh-pages

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3